/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtBarChart: typeof import('./src/components/core/charts/art-bar-chart/index.vue')['default']
    ArtBreadcrumb: typeof import('./src/components/core/layouts/art-breadcrumb/index.vue')['default']
    ArtCountTo: typeof import('./src/components/core/text-effect/art-count-to/index.vue')['default']
    ArtDragVerify: typeof import('./src/components/core/forms/art-drag-verify/index.vue')['default']
    ArtException: typeof import('./src/components/core/views/exception/ArtException.vue')['default']
    ArtFastEnter: typeof import('./src/components/core/layouts/art-fast-enter/index.vue')['default']
    ArtGlobalComponent: typeof import('./src/components/core/layouts/art-global-component/index.vue')['default']
    ArtHeaderBar: typeof import('./src/components/core/layouts/art-header-bar/index.vue')['default']
    ArtHorizontalMenu: typeof import('./src/components/core/layouts/art-menus/art-horizontal-menu/index.vue')['default']
    ArtIconButton: typeof import('./src/components/core/widget/art-icon-button/index.vue')['default']
    ArtLineChart: typeof import('./src/components/core/charts/art-line-chart/index.vue')['default']
    ArtLogo: typeof import('./src/components/core/base/art-logo/index.vue')['default']
    ArtMenuRight: typeof import('./src/components/core/others/art-menu-right/index.vue')['default']
    ArtMixedMenu: typeof import('./src/components/core/layouts/art-menus/art-mixed-menu/index.vue')['default']
    ArtPageContent: typeof import('./src/components/core/layouts/art-page-content/index.vue')['default']
    ArtRingChart: typeof import('./src/components/core/charts/art-ring-chart/index.vue')['default']
    ArtSidebarMenu: typeof import('./src/components/core/layouts/art-menus/art-sidebar-menu/index.vue')['default']
    ArtSvgIcon: typeof import('./src/components/core/base/art-svg-icon/index.vue')['default']
    ArtTable: typeof import('./src/components/core/tables/art-table/index.vue')['default']
    ArtUserMenu: typeof import('./src/components/core/layouts/art-header-bar/widget/ArtUserMenu.vue')['default']
    ArtWorkTab: typeof import('./src/components/core/layouts/art-work-tab/index.vue')['default']
    AuthTopBar: typeof import('./src/components/core/views/login/AuthTopBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HorizontalSubmenu: typeof import('./src/components/core/layouts/art-menus/art-horizontal-menu/widget/HorizontalSubmenu.vue')['default']
    LoginLeftView: typeof import('./src/components/core/views/login/LoginLeftView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSubmenu: typeof import('./src/components/core/layouts/art-menus/art-sidebar-menu/widget/SidebarSubmenu.vue')['default']
    ThemeSvg: typeof import('./src/components/core/theme/theme-svg/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
